import{a as g,S as v,i as f}from"./assets/vendor-CQBu-7cX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";async function h(o,t,i){const s={params:{key:"51390030-b864bce351d7615980478c23b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:t}};return(await g.get("",s)).data}const n={gallery:document.querySelector(".js-gallery"),form:document.querySelector(".js-form"),loader:document.querySelector(".loader"),loadMoreButton:document.querySelector(".js-load-more-button")};function m(o){return o.map(({webformatURL:t,largeImageURL:i,tags:s,likes:e,views:r,comments:a,downloads:M})=>`
      <li>
        <a href="${i}">
          <img src="${t}" alt="${s}" loading="lazy" width="360" height="200"/>
        </a>
        <div>
          <p>likes: <span>${e}</span></p>
          <p>views: <span>${r}</span></p>
          <p>comments: <span>${a}</span></p>
          <p>downloads: <span>${M}</span></p>
        </div>
      </li>`).join("")}let u=null;function y(){u?u.refresh():u=new v(".js-gallery a")}function w(){n.gallery.innerHTML=""}function L(){n.loader.classList.remove("is-hidden")}function b(){n.loader.classList.add("is-hidden")}function B(){n.loadMoreButton.classList.remove("is-hidden")}function p(){n.loadMoreButton.classList.add("is-hidden")}function q(){const{height:o}=n.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2+20,behavior:"smooth"})}let l=1,d=15,c=null;async function S(o){if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!c){f.error({message:"enter a search query to find images",position:"topRight"});return}L(),l=1,w(),p();try{const{data:t}=await h(c,l,d);if(console.log(t),!t.hits.length){f.error({message:"Sorry, there are no images matching your search query. Please try again",position:"topRight"});return}const i=m(t.hits);n.gallery.innerHTML=i,y(),t.totalHits>d?B():p()}catch(t){console.error("Error fetching images:",t)}finally{b()}}async function P(){L();try{l++;const{data:o}=await h(c,l,d);n.gallery.insertAdjacentHTML("beforeend",m(o.hits)),y(),q();const t=Math.ceil(o.totalHits/d);l>=t&&(p(),f.info({message:"No more images found",position:"topRight"}))}catch(o){console.log(o)}finally{b()}}n.form.addEventListener("submit",S);n.loadMoreButton.addEventListener("click",P);
//# sourceMappingURL=index.js.map
